# creating ND-Array

In [1]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [2]:
! pip install numpy

  Using cached numpy-2.3.4-cp313-cp313-win_amd64.whl.metadata (60 kB)
Using cached numpy-2.3.4-cp313-cp313-win_amd64.whl (12.8 MB)


In [3]:
import numpy as np

In [4]:
arr1=np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [5]:
type(arr1)

numpy.ndarray

In [6]:
arr2=np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
type(arr2)

numpy.ndarray

In [8]:
arr3=np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
arr4=np.ones(2,3)
arr4

TypeError: Cannot interpret '3' as a data type

In [10]:
arr4=np.ones((2,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
type(arr4)

numpy.ndarray

In [12]:
arr5=np.identity(5)

In [13]:
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
arr6=np.arange(16)

In [15]:
arr6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [16]:
arr7=np.arange(5,16,2)
arr7

array([ 5,  7,  9, 11, 13, 15])

In [17]:
arr8=np.linspace(10,20,10)
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])